### ISSUE TITLE
Adapter latest version don't run locally for OSX

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [layer5io/meshery-istio#222] opened 2021-05-29 11:35 UTC
**Description**
Latest version of Istion Adapter when ran locally don't work for OSX few changes needs to be done.It gives an error as below:

```
DEBUG=true GOPROXY=direct GOSUMDB=off go run main.go
# github.com/docker/docker/pkg/term
../../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
make: *** [run] Error 2
```

**Expected Behavior**
If the issue is just for the OSX then it needs to be added in the Setup documentation by creating one as it is missing right now or if could be fixed without the interference in working in other OS then needs to be fixed.

**Enviroment:**
 - OS: OSX
 - Version: latest
 - Device: MacBook

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment] 2021-06-02 22:10
Thanks for this @Ayush-Khandelwal-007. Turns out that this is a duplicate of #212

**Comment by kumarabd** [comment] 2021-06-04 08:37
refer - https://github.com/layer5io/meshery-istio/issues/212

**Closed by kumarabd** 2021-06-04 08:37 UTC
Labels: issue/duplicate, kind/bug
